### ISSUE TITLE
Non-image files in media library

### ISSUE THREAD

**Issue by mrleemon** [nosilver4u/imsanity#19]
With the latest version one can see the images current dimensions in media library list mode. But all non-image files such as PDFs or video files throw two warnings when `define('WP_DEBUG', true)`: 

```
Notice: Undefined index: file in /xxxxxx/wp-content/plugins/imsanity/media.php on line 75
Notice: Undefined index: file in /xxxxxx/wp-content/plugins/imsanity/media.php on line 81
```

**Comment by nosilver4u** [comment]
Thanks for reporting that, I'll get it fixed for the next release!

**Comment by nosilver4u** [comment]
fix committed to GitHub, should also resolve problems with missing metadata
