### ISSUE TITLE
make PNG to JPG conversion skip transparent images

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/imsanity#2]
Currently, the plugin will just fill in with a white background, but it has been suggested that perhaps it should skip them instead. Either behavior should be able to be toggled by defining a constant.

**Comment by cfoellmann** [comment]
My suggestion: Avoid constants wherever possible. Add a filter instead.

I would vote to make skipping the default behavior

**Comment by nosilver4u** [comment]
I think that makes it harder for "average" users to change it, wouldn't you think?
Although really, we're mostly addressing "edge" cases, so perhaps these aren't average users that want to override the defaults. I tend to do both, have constants for folks who can't handle a filter, and filters for devs who have the skill and want the flexibility. So perhaps we should go that route?

**Comment by cfoellmann** [comment]
the problem with constants is that overwriting is prohibited but possible and leads to unpredictable consequences.
Filters on the other side can be removed later. e.g. on a site after it was set for the network.

**Comment by nosilver4u** [comment]
PNGs with alpha will be skipped by default in 2.7 with filter to override.
