### ISSUE TITLE
use "original" instead of "scaled" if available

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/imsanity#22]
For existing images, if the image has been scaled and the original is still available, it would be better for quality if we used the original as the source.

**Comment by nosilver4u** [comment]
all done!

**Comment by charlesdeb** [comment]
I am testing this functionality, and it still appears to be working on the "-scaled" files, and not the original one.

```
wpe-user@my-site.ssh.wpengine.net:~/sites/my-site/wp-content/uploads/2023/01$ ll *2863*
-rw-rw-r-- 1 wpe-user wpe-user   135227 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-1536x1024.jpg
-rw-rw-r-- 1 wpe-user wpe-user   205736 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-2048x1365.jpg
-rw-rw-r-- 1 wpe-user wpe-user    26510 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-60x60.jpg
-rw-rw-r-- 1 wpe-user wpe-user    61672 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-768x512.jpg
-rw-rw-r-- 1 wpe-user wpe-user   317519 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-scaled.jpg
-rw-rw-r-- 1 wpe-user wpe-user 17414430 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited.jpg

wpe-user@my-site.ssh.wpengine.net:~/sites/my-site/wp-content/uploads/2023/01$ # after resizing with imsanity in the WP UI
wpe-user@my-site.ssh.wpengine.net:~/sites/my-site/wp-content/uploads/2023/01$ ll *2863*
-rw-rw-r-- 1 wpe-user wpe-user   135227 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-1536x1024.jpg
-rw-rw-r-- 1 wpe-user wpe-user   205736 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-2048x1365.jpg
-rw-rw-r-- 1 wpe-user wpe-user    26510 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-60x60.jpg
-rw-rw-r-- 1 wpe-user wpe-user    61672 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-768x512.jpg
-rw-rw-r-- 1 wpe-user wpe-user   185101 Dec  5 12:30 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited-scaled.jpg
-rw-rw-r-- 1 wpe-user wpe-user 17414430 Feb 24  2023 2022-10-13_BAS_EMST_Emma_Stark-2863-_edited.jpg
```

I have deleted a few thumbnails for brevity, but as you can see, the big 17MB file was uploaded on Feb 24, and WP 
- created a `-scaled` version that was more like 300KB
- created a bunch of `.jpg` thumbnails

When I used imsanity within the WP UI, then you can see from the dates in the listing that imsanity appears to have just resized the `-scaled` version (down to 185KB), and left all the others alone. I don't mind that it hasn't touched the smaller thumbnails - but for me, the whole point of using this plugin is to scale down that  17MB file - not further optimise an already resize 300KB down to 185KB. 

I'm using version 2.8.3 of the plugin.

Or am I missing something here?

**Comment by charlesdeb** [comment]
Update: I am missing something. I just needed to have the 'delete original images' setting checked.

**Comment by nosilver4u** [comment]
@charlesdeb Glad you figured it out :) This issue was regarding using the pre-scaled original to generate a new (smaller) "full size" (-scaled) image, instead of simply re-scaling the scaled version. In no case does Imsanity ever modify the original pre-scaled image unless you tell it to delete the originals.
