### ISSUE TITLE
imsanity_skip_image question

### ISSUE THREAD

**Issue by luuktimmermans** [nosilver4u/imsanity#25]
Hi!

How would I use the `imsanity_skip_image` to exclude all gif images from being optimized?

**Comment by nosilver4u** [comment]
If you're not familiar with filters, I recommend you take a look at https://ewww.io/2016/03/16/ewww-image-optimizer-filters-part-1/
You might also reference https://gist.github.com/nosilver4u/848591cf7fb2671f17f86803a1a5e318 as an example of a filter targeting GIF images--though it's not perfect, as any image with '.gif' anywhere in the filename would be affected.

If that is beyond you, then you'd need to hire a developer to implement that.
