### ISSUE TITLE
Option to convert to webp

### ISSUE THREAD

**Issue by drdogbot7** [nosilver4u/imsanity#27]
It would be super rad if there was an option to convert images to webp.

That is all.

**Comment by nosilver4u** [comment]
Hi @drdogbot7,
Thanks for the suggestion, but we already have a plugin that does that :)
Imsanity is primarily focused on saving disk space by resizing images, or converting unwieldy formats like BMP. I recommend you check out EWWW Image Optimizer if you want WebP conversion, we've made sure it works well with Imsanity.
