### ISSUE TITLE
change default size settings

### ISSUE THREAD

**Issue by nosilver4u** [nosilver4u/imsanity#3]
It seems 2048 was probably used as it is a typical binary multiplier. Not sure if that's the correct term, but it is a number that corresponds to memory measurements, disk space measurements (the ones used by programmers, not disk manufacturers), and the like. For example, 512, 1024, 1536, 2048, etc.

However, when it comes to screen resolution, it isn't very practical, as most screens are 1920px or smaller, so it has been suggested that we default to 1920 rather than 2048. Such a change will not impact existing users, only new ones. Still accepting feedback on the issue for a while.

**Comment by cfoellmann** [comment]
putting aside the value itself (I have no opinion/insight on that) I would like to suggest replacing the constants with filters!

https://github.com/nosilver4u/imsanity/blob/cd1db1e3da4cb61c28b5eee024a7a58984e4a493/imsanity.php#L29-L33

**Comment by nosilver4u** [comment]
Per my comments on the PNG transparency, I think it would be preferable to have both. Filters for the folks who can handle them, constants for those who cannot. The quality level is already a core WP filterable value, but it would be good to allow the other settings to have filters for sure.

Besides that, those are simply the defaults. Once a person configures Imsanity, their options always override the defaults.

**Comment by nosilver4u** [comment]
The defaults were changed ages ago and I forgot about this. However, the next release is going to contain a filter that will allow folks to override the dimensions for any given image/scenario.
